### ISSUE TITLE
Integration error, please help

### ISSUE THREAD

**Issue by murendie** [kayako/whmcs-integration#34]
[Sun Dec 06 20:46:53 2015] [error] [client 105.7.75.107] PHP Warning:  Missing argument 8 for kyTicket::getAll(), called in /var/www/my/modules/support/kayako/fetchOpenTickets.php on line 35 and defined in /var/www/my/modules/support/kayako/API/kyTicket.php on line 648
[Sun Dec 06 20:46:53 2015] [error] [client 105.7.75.107] PHP Warning:  Missing argument 9 for kyTicket::getAll(), called in /var/www/my/modules/support/kayako/fetchOpenTickets.php on line 35 and defined in /var/www/my/modules/support/kayako/API/kyTicket.php on line 648
[Sun Dec 06 20:46:56 2015] [error] [client 105.7.75.107] PHP Fatal error:  Uncaught exception 'kyException' with message 'HTTP error: 400' in /var/www/my/modules/support/kayako/API/kyRESTClient.php:195\nStack trace:\n#0 /var/www/my/modules/support/kayako/API/kyRESTClient.php(230): kyRESTClient->processRequest('/Tickets/Ticket', 'POST', Array, Array, Array)\n#1 /var/www/my/modules/support/kayako/API/kyTicket.php(696): kyRESTClient->post('/Tickets/Ticket', Array, Array)\n#2 /var/www/my/modules/support/kayako/fetchOpenTickets.php(37): kyTicket::getTicketCount(Object(kyResultSet), Object(kyTicketStatus), Array, Array, NULL)\n#3 /var/www/my/includes/hooks/hooks.php(35): include_once('/var/www/my/mod...')\n#4 /var/www/my/includes/hookfunctions.php(0): hook_clientarea_details(Array)\n#5 /var/www/my/includes/classes/WHMCS/ClientArea.php(0): run_hook()\n#6 /var/www/my/includes/classes/WHMCS/ClientArea.php(0): WHMCS\\ClientArea->runOutputHooks()\n#7 /var/www/my/clientarea.php(0): WHMCS\\ClientArea->output()\n#8 {main}\n\nNext exception 'kyException' with message 'HTTP error: 400' in /var/www/my/includes/cl in /var/www/my/includes/classes/WHMCS/Terminus.php on line 0
root@venus:/var/www/my/modules/support/kayako#

**Comment by kostyukdv** [comment]
Have same issue.

Kayako 4.72
WHMCS 5.3.14
