### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by kostyukdv** [kayako/whmcs-integration#44]
After update to the latest version of whmcs-integration I faced with issue

Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/billingh/public_html/modules/support/kayako/API/kyHelpers.php:31 Stack trace: #0 /home/billingh/public_html/modules/support/kayako/API/kyHelpers.php(31): SimpleXMLElement->__construct('<?xml version="...') #1 /home/billingh/public_html/modules/support/kayako/API/kyRESTClient.php(202): ky_xml_to_array('<?xml version="...') #2 /home/billingh/public_html/modules/support/kayako/API/kyRESTClient.php(220): kyRESTClient->processRequest('/Base/Departmen...', 'GET', Array) #3 /home/billingh/public_html/modules/support/kayako/API/kyObjectBase.php(196): kyRESTClient->get('/Base/Departmen...', Array) #4 /home/billingh/public_html/modules/support/kayako/supporttickets.php(20): kyObjectBase::getAll() #5 /home/billingh/public_html/supporttickets.php(0): unknown() #6 {main} Next exception 'Exception' with message 'String could not be parsed as XML' in /home/billingh/public_html/includes/classes/WHMCS/Terminus.php:0 Stack trace: #0 /home in /home/billingh/public_html/includes/classes/WHMCS/Terminus.php on line 0

**Comment by bellwood** [comment]
Same here:

[~]# php -v
PHP 5.6.18 (cli) (built: Mar  2 2016 16:06:04)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

WHMCS Version: 6.1.1

**Comment by bellwood** [comment]
Also, FWIW:

```

Strict Standards: Declaration of kyDepartment::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyDepartment.php on line 0

Strict Standards: Declaration of kyStaff::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyStaff.php on line 0

Strict Standards: Declaration of kyStaffGroup::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyStaffGroup.php on line 0

Strict Standards: Declaration of kyTicket::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyTicket.php on line 0

Strict Standards: Declaration of kyTicket::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicket.php on line 0

Strict Standards: Declaration of kyTicketAttachment::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyTicketAttachment.php on line 0

Strict Standards: Declaration of kyTicketAttachment::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicketAttachment.php on line 0

Strict Standards: Declaration of kyTicketAttachment::get() should be compatible with kyObjectBase::get($id) in /home/billing/public_html/modules/support/kayako/API/kyTicketAttachment.php on line 0

Strict Standards: Declaration of kyTicketCustomFieldGroup::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicketCustomFieldGroup.php on line 0

Strict Standards: Declaration of kyTicketNote::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyTicketNote.php on line 0

Strict Standards: Declaration of kyTicketNote::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicketNote.php on line 0

Strict Standards: Declaration of kyTicketNote::get() should be compatible with kyObjectBase::get($id) in /home/billing/public_html/modules/support/kayako/API/kyTicketNote.php on line 0

Strict Standards: Declaration of kyTicketPost::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyTicketPost.php on line 0

Strict Standards: Declaration of kyTicketPost::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicketPost.php on line 0

Strict Standards: Declaration of kyTicketPost::get() should be compatible with kyObjectBase::get($id) in /home/billing/public_html/modules/support/kayako/API/kyTicketPost.php on line 0

Strict Standards: Declaration of kyTicketTimeTrack::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyTicketTimeTrack.php on line 0

Strict Standards: Declaration of kyTicketTimeTrack::getAll() should be compatible with kyObjectBase::getAll($search_parameters = Array) in /home/billing/public_html/modules/support/kayako/API/kyTicketTimeTrack.php on line 0

Strict Standards: Declaration of kyTicketTimeTrack::get() should be compatible with kyObjectBase::get($id) in /home/billing/public_html/modules/support/kayako/API/kyTicketTimeTrack.php on line 0

Strict Standards: Declaration of kyUser::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyUser.php on line 0

Strict Standards: Declaration of kyUserGroup::createNew() should be compatible with kyObjectBase::createNew() in /home/billing/public_html/modules/support/kayako/API/kyUserGroup.php on line 0
```

**Comment by mansiwason** [comment]
@bellwood you can disable strict mode errors from your mysql server or the config file of whmcs - error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING ^ E_STRICT);

@bellwood @kostyukdv For String could not be parsed as XML we need to check the cause of this issue. And for this Can you please create a case in https://support.kayako.com with the detail of issue where are you getting this error? 

Thanks, 
Mansi

**Comment by bellwood** [comment]
@mansiwason I know how to hide the strict mode errors but wanted to report the problem with the code - it should be fixed

Thank you =)

**Comment by hukphil** [comment]
Did this ever get fixed or is dead?
