### ISSUE TITLE
Problem with retrieving user Email

### ISSUE THREAD

**Issue by vrert** [kayako/whmcs-integration#45]
When I try to create a ticket I faced with issue

 PHP Fatal error:  Uncaught exception 'kyException' with message 'Values for API fields 'email' is required for this operation to complete.' in /var/www/clients/client0/web4/web/modules/support/kayako/API/kyObjectBase.php:492\nStack trace:\n#0 /var/www/clients/client0/web4/web/modules/support/kayako/API/kyTicket.php(589): kyObjectBase->checkRequiredAPIFields(true)\n#1 /var/www/clients/client0/web4/web/modules/support/kayako/API/kyObjectBase.php(255): kyTicket->buildData(true)\n#2 /var/www/clients/client0/web4/web/modules/support/kayako/submitticket.php(127): kyObjectBase->create()\n#3 /var/www/clients/client0/web4/web/submitticket.php(0): unknown()\n#4 {main}\n\nNext exception 'kyException' with message 'Values for API fields 'email' is required for this operation to complete.' in /var/www/clients/client0/web4/web/includes/classes/WHMCS/Terminus.php:0\nStack trace:\n#0 [internal function]: WHMCS\\Terminus->whmcsExceptionHandler(Object(kyException))\n#1 {main}\n  thrown in /var/www/clients/client0/web4/web/includes/classes/WHMCS/Terminus.php on line 0, referer: http://whmcs.localhost/submitticket.php?step=2

**Comment by vrert** [comment]
Looks like bug was because of WHMCS version, last update fixed it
